baseURL = "https://www.joshasplund.com/"
languageCode = "en-us"
title = "Josh Asplund"
theme = "paperback"
googleAnalytics = "UA-7687230-3"

[params]
AuthorName = "Josh Asplund"
Tagline = "Digital sociology and other stuff"
HomepagePosts = 3
GithubUsername = "joshuata"
TwitterUsername = "josh_asplund"
